### PR TITLE
Upgrade @glimmer/compiler

### PR DESCRIPTION
**Pull request by pittst3r**
- [x] Bump `@glimmer/compiler` version
- [x] Update extract pragma plugin
- [x] Publish https://github.com/glimmerjs/glimmer-vm/pull/557
- [x] Bump `@glimmer/compiler` version

### CODE REVIEW

**Comment by twokul** [comment]
seems like test is failing

```
not ok 8 glimmer-template-precompiler > pragma tag extraction (`glimmer-custom-component-manager` feature flag) > custom component manager id is extracted from pragma tag
```

**Comment by pittst3r** [comment]
@twokul Yeah, it's because https://github.com/glimmerjs/glimmer-vm/pull/557 needs to be published and I need to bump the `@glimmer/compiler` version again.

**Comment by pittst3r** [comment]
Okay, this is ready for review and merge now.

**Review by rwjblue — CHANGES_REQUESTED** [review]
Since we changed the way the AST plugin works, we need to bump the `peerDependencies` minimum also

**Comment by pittst3r** [comment]
✅

**Review by rwjblue — APPROVED** [review]

**Pull request merged**
